### ISSUE TITLE
Phase 1

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/week8-wdgaf#2]
Initialise project
- [x] Set up Travis, ESlint, gitignore, ESlintignore, 
- [x] Create folder and file structure #3 
- [x] Readme file #4 
- [x] npm install tape, tap-spec, nyc, express, express-session #7  

Set up database
- [x] build.js, #5 
- [x] build.sql, #8
- [x] conndectiondb #9

Setup express 
- [x] setup app.js #10 
- [x] index.js #11
- [x] setup main.hbs #12
- [x] Two views: portal.hbs #13
- [x] profiles.hbs #14
- [x] Use dummy data  for model/index.js #15

**Comment by afifisuha** [comment]
done
