### ISSUE TITLE
phase 2

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/week8-wdgaf#29]
- [x] Make query to database for graduate data #24 
- [x] Replace dummy data with database data #25
- [x] Make 404 page #26
- [x] Make 500 page #27
- [x] Make portal page with an each loop #28 
- [x] Make header and footer #30

**Comment by matthall8** [comment]
Completed in latest commit.
