### ISSUE TITLE
phase 4

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/week8-wdgaf#57]
- [x] Logout button - removes the cookie. #55
- [x] customise main.hbs to to say `welcome ${github name}` #56
- [x] personalise the edit page based on cookie. #57

**Comment by matthall8** [comment]
Phase complete. Closing.
